-- NOT A MIGRATION. DO NOT APPLY THIS AS PART OF ANY RELEASE.
--
-- This file exists for exactly one purpose: to prove, once, that the trusted
-- Leader migration executor can authenticate to the Supabase Management API and
-- receive a response. It is numbered 999 so it sits outside the real migration
-- sequence (001-042) and can never be mistaken for the next migration to apply.
--
-- It changes nothing. There is no DDL, no GRANT, no INSERT, UPDATE or DELETE,
-- no transaction control, and no second statement. `select 1` is the whole
-- artifact: if it runs, the credential, the endpoint and the transport work; if
-- it does not, none of them do, and nothing about the database has changed
-- either way.
--
-- WHY IT GOES THROUGH THE EXECUTOR AT ALL. The point is not to learn whether a
-- token can reach an API - curl would answer that. The point is to exercise the
-- whole governed path end to end while the consequence of a mistake is zero:
-- committed artifact, exact branch, exact commit, exact path, exact SHA-256,
-- a dedicated owner approval, the executor's own checks, one request, an
-- immutable audit record, and the approval consumed so it cannot be replayed.
-- The first time that path carries something that matters should not be the
-- first time it has carried anything.
--
-- There is no rollback file because there is nothing to roll back.

select 1;
